kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-gp2
  namespace: sandbox
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: false
reclaimPolicy: "Delete"
parameters:
  type: gp2
  fsType: ext4
