## Onaje Baxley 
## 6/18/18
## Config for cassandra helm package, set to run at 75% capacity
## of recommended dev settings.
#
## Install command: helm install --namespace cassandra -n cassandra \
##  -f <this-file> incubator/cassandra
## 
## Prerequisites: - creation of EBS gp2 StorageClass

## Cassandra image version
image:
    repo: "cassandra"
    tag: "3"
    pullPolicy: "Always"
## Cassandra-instance config parameters
config:
    cluster_name: "cassandra"
    cluster_size: 3
    seed_size: 2
    # num_tokens: 256
    dc_name: "DC1"
    rack_name: "RAC1"
    # endpoint_snitch: "Ec2Snitch"
    max_heap_size: 1536M
    heap_new_size: 384M
    # start_rpc: false
    ports:
        cql: 9042
        thrift: 9160
        # agent: None

## Kubernetes dynamic PV settings
persistence:
    enabled: true
    storageClass: "ebs-gp2"
    accessMode: "ReadWriteOnce"
    size: 12Gi

## Kubernetes resource requests/limits
resources:
    requests:
        memory: 3Gi
        cpu: 1.5
    limits:
        memory: 3Gi
        cpu: 1.5

## Kubernetes Service type
service:
    type: ClusterIP
podManagementPolicy: "OrderedReady"
updateStrategy:
    type: "RollingUpdate"

## Label-based matching determines K8S nodes to launch pods
selector:
    nodeSelector:
        kops.k8s.io/instancegroup: nodes

